apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
home: https://helm.sh/helm
maintainers:
  - email: branco.bruyneel@student.howest.be
    name: Branco Bruyneel
name: imdb-services
sources:
  - https://github.com/helm/helm
version: 2.1.3
